name: m3
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.2

dependencies:
  chaleno: ^0.0.6
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_staggered_grid_view: ^0.6.2
  image_fade: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
